"""CLI command package — registers all subcommands on `main`."""

from crossmem.commands.core import forget, graph, ingest, init, save, search, serve, stats, update
from crossmem.commands.doctor import doctor
from crossmem.commands.hooks import (
    COPILOT_CONTENT_MARKER_END,
    COPILOT_CONTENT_MARKER_START,
    HOOK_MATCHER,
    HOOK_MATCHER_LEGACY,
    INSTRUCTION_LINE,
    INSTRUCTION_MARKER,
    PROMPT_SEARCH_BUDGET,
    PROMPT_SEARCH_MAX_RESULTS,
    PROMPT_SEARCH_MIN_RANK,
    PROMPT_SEARCH_MIN_WORDS,
    _append_instruction,
    _build_copilot_block,
    _build_recall_output,
    _claude_settings_path,
    _copilot_global_path,
    _find_crossmem_bin,
    _get_recall_content,
    _inject_copilot_block,
    _install_hook_claude,
    _install_hook_copilot,
    _install_hook_copilot_agent,
    _parse_block_timestamp,
    _read_settings,
    _remove_instruction,
    _replace_instruction_block,
    _source_tier,
    _strip_copilot_block,
    _write_settings,
    install_hook,
    install_instructions,
    prompt_search,
    recall,
)
from crossmem.commands.setup import setup

__all__ = [
    # Core commands
    "graph",
    "init",
    "ingest",
    "save",
    "search",
    "serve",
    "stats",
    "forget",
    "update",
    # Hook commands
    "install_hook",
    "install_instructions",
    "prompt_search",
    "recall",
    # Setup command
    "setup",
    # Doctor command
    "doctor",
    # Constants (used by tests)
    "COPILOT_CONTENT_MARKER_END",
    "COPILOT_CONTENT_MARKER_START",
    "HOOK_MATCHER",
    "HOOK_MATCHER_LEGACY",
    "INSTRUCTION_LINE",
    "INSTRUCTION_MARKER",
    "PROMPT_SEARCH_BUDGET",
    "PROMPT_SEARCH_MAX_RESULTS",
    "PROMPT_SEARCH_MIN_RANK",
    "PROMPT_SEARCH_MIN_WORDS",
    # Private helpers (re-exported for tests)
    "_append_instruction",
    "_build_copilot_block",
    "_build_recall_output",
    "_claude_settings_path",
    "_copilot_global_path",
    "_find_crossmem_bin",
    "_get_recall_content",
    "_inject_copilot_block",
    "_install_hook_claude",
    "_install_hook_copilot",
    "_install_hook_copilot_agent",
    "_parse_block_timestamp",
    "_read_settings",
    "_remove_instruction",
    "_replace_instruction_block",
    "_source_tier",
    "_strip_copilot_block",
    "_write_settings",
]
